export interface IGameTemplate {
    sGameType: string,
	sGameVersion: string,
	sBikeVersion: string,
	sAnimationTable: number,
	gBuffer1: number,
	gBuffer2: number,
	gBuffer3: number,
	gPartyCount: number,
	gParty: number,
	gEnemyParty: number,
	gSprite: number,
	gTrainerCard: number,
	gSendBuffer: number,
	gPlayerData: number,
	gCameraX: number,
	gCameraY: number,
	gPlayerSprite: number,
	gSpriteData: number,
	gMapBank: number,
	gMapHeader: number,
	gSpecialVar_8000: number,
	gMainCallback: number,
	gLockControls: number,
	gPaletteUnfaded: number,
	gPaletteFaded: number,
	gGraphicsInfo?: number,
	sObjectEventSpritePalettes?: number,
	gObjectEvents: number,
	
	gScriptData: number,
	gTextData: number,
	gMultiChoiceData: number,
	gNativeData: number,
	gScriptLoad: number,
	gSelectedObjectEvent: number,
	gPlayerRomSpriteLocation: number,
}